name: Update Tag Version

on:
  push:
    branches:
      - master

jobs:
  update_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags --force --prune
          git describe --abbrev=0 --tags "$(git rev-list --tags --max-count=1)"

      - name: Generate new tag version
        id: generate_new_tag
        run: |
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            OLD_TAG="${{ steps.get_latest_tag.outputs.tag }}"
            OLD_VERSION="${OLD_TAG:1}"
            IFS='.' read -ra VERSION_PARTS <<< "$OLD_VERSION"
            MAJOR="${VERSION_PARTS[0]}"
            MINOR="${VERSION_PARTS[1]}"
            PATCH=$((VERSION_PARTS[2] + 1))
            NEW_TAG="v$MAJOR.$MINOR.$PATCH"
            echo "::set-output name=new_tag::$NEW_TAG"
          fi

      - name: Create Git tag
        run: |
          if [ -n "${{ steps.generate_new_tag.outputs.new_tag }}" ]; then
            git tag ${{ steps.generate_new_tag.outputs.new_tag }}
            git push origin ${{ steps.generate_new_tag.outputs.new_tag }}
          fi
