name: Update Tag

on:
  push:
    branches:
      - master

jobs:
  update_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine previous tag version
        id: previous_tag
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0)
          echo "::set-output name=previous_tag::$PREVIOUS_TAG"

      - name: Increment tag version
        id: increment_version
        run: |
          PREVIOUS_TAG=$PREVIOUS_TAG
          IFS='.' read -ra VERSION_PARTS <<< "$PREVIOUS_TAG"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=$((${VERSION_PARTS[2]} + 1))
          NEW_TAG="$MAJOR.$MINOR.$PATCH"
          echo "::set-output name=new_tag::$NEW_TAG"

      - name: Create and push updated tag
        run: |
          git tag ${{ steps.increment_version.outputs.new_tag }}
          git push origin ${{ steps.increment_version.outputs.new_tag }}
