name: Create Git Tag
on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Git tag
        run: |
          git tag -a ${{ github.ref }} -m "Automated tag for ${{ github.ref }}"
          git push origin ${{ github.ref }}
